services:
  duck-hack.frontend-admin:
    build: ./frontend-admin
    container_name: duck-hack.frontend-admin
    networks:
      - npm
      - duck-hack.frontend-admin-net

  duck-hack.frontend-user:
    build: ./frontend-user
    container_name: duck-hack.frontend-user
    networks:
      - npm
      - duck-hack.frontend-user-net

  duck-hack.backend:
    build: ./backend
    container_name: duck-hack.backend
    networks:
      - npm
      - duck-hack.backend-net

networks:
  duck-hack.frontend-admin-net:
    name: duck-hack.frontend-admin-net
    driver: bridge
  duck-hack.frontend-user-net:
    name: duck-hack.frontend-user-net
    driver: bridge
  duck-hack.backend-net:
    name: duck-hack.backend-net
    driver: bridge
  npm:
    external: true