services:
  frontend-admin:
    build: ./frontend-admin
    ports:
      - "89:80"
    volumes:
      - ./frontend-admin:/app

  frontend-user:
    build: ./frontend-user
    ports:
      - "82:80"
    volumes:
      - ./frontend-user:/app

  backend:
    build: ./backend
    ports:
      - "83:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
